version: "3.8"
services:
  php:
    build: ./docker/php
    container_name: app
    volumes:
      - ./:/var/www/publisher
  nginx:
    build: ./docker/nginx
    container_name: nginx
    volumes:
      - ./:/var/www/publisher
    depends_on:
      - php
    ports:
      - "8000:80"
